# Lines starting with # are comments

# Always extract audio
-i
-x
-f "bestaudio"

#--audio-multistreams
#-v
#--quiet
#--no-progress
--no-warnings

--audio-format opus
--audio-quality 0

# Save all videos under YouTube directory in your home directory
-o "./library/music/%(playlist_title)s/%(artist,uploader|Unknown Artist)s - %(title)s.%(ext)s"
-P "./library/music/.tmp/"

# YouTube Music optimized client
#--extractor-args "youtube:player_client=android"

# Archive to avoid redownloads
#--download-archive downloaded-songs-archive.txt

# Cookies for safety
#--cookies-from-browser firefox

# Polite throttling
--sleep-interval 10
--max-sleep-interval 25
--throttled-rate 100K

--concurrent-fragments 1
--fragment-retries 5
--retries 10

# Network robustness
--socket-timeout 30

# Metadata
--embed-metadata
--embed-thumbnail
--add-metadata

#--progress
#--external-downloader aria2c
#--external-downloader-args "-x 4 -j 8"